### ISSUE TITLE
Prepare Jakarta Interceptors for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/interceptor-api#34]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [ ] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
Staging release done: https://oss.sonatype.org/content/repositories/staging/jakarta/interceptor/jakarta.interceptor-api/1.2.5/

**Comment by arjantijms** [comment]
* [Spec PR 1](https://github.com/jakartaee/specifications/pull/52)
* [Spec PR 2](https://github.com/jakartaee/specifications/pull/53)

**Comment by arjantijms** [comment]
Note that there's no standalone TCK for Interceptors, but the full CTS will be used instead.

**Comment by m0mus** [comment]
@arjantijms Do you have a job to run full CTS?

**Comment by arjantijms** [comment]
> @arjantijms Do you have a job to run full CTS?

Not yet, I'm looking at how to do this exactly.

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/18)

**Comment by edbratt** [comment]
For a CI, you can use results from Eclipse GlassFish 5.1, tested against either [full profile](https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-certification/6/) or [web profile](https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-certification-web/1/junit-reports-with-handlebars/testSuitesOverview.html). The TCK used is [here](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip) (for your SHA256 calculation). Eclipse GlassFish will need to preserve these. Once we know where, we can publish the URL so others can refer to it.
For the revised API, to assure quality, you follow the same approach as with stand-alone TCKs -- build a test Eclipse Glassfish binary, feed that build into a CI test runner for CTS (instead of stand-alone TCK) -- My suggestion would be to build a Web Profile edition of Eclipse GlassFish and then run the Web Profile CTS. It won't take as long. You don't need to preserve these quality results -- longer than you think you want to be able to refer to them. The CI results from above, do need to be kept in stable storage. There is a job setup in Jakarta EE TCK CI that you can use ([jakartaeetck-certification-web](https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification-web/)) -- I think you can trigger this (maybe manually) after you have a build in the Interceptors CI, or you can clone that job and run it here in the CI for Interceptors.

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549722)
