### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Interceptors 2.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/interceptor-api#71]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
   [Eclipse GlassFish 6.0](https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-6.0.0.zip)
- [x] Specification Name, Version and download URL
  [Jakarta Interceptors 2.0](https://jakarta.ee/specifications/interceptors/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta EE Platform TCK 9.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0-RC1.zip, SHA-256: `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392`
- [x] Public URL of TCK Results Summary
  There is no stand-alone TCK for this specification. See Full Platform CTS for results.
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-interceptors/2.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  Oracle JDK 1.8.0_251
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Alpine Linux v3.12
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kazumura** [comment]
@arjantijms  
Could you update the TCK download URL and result as mentioned at https://github.com/jakartaee/specifications/pull/233#issuecomment-721148600 ?

**Comment by arjantijms** [comment]
@kazumura Thank you for the reference. Can you check whether I updated correctly? Thank you very much.

**Comment by kazumura** [comment]
@arjantijms   
Thanks. Looks fine.

**Comment by edbratt** [comment]
I'd recommend we reference the TCK 9.0 RC-1 since that won't change ([here](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0-RC1.zip)). The SHA of the TCK is the same, this release is just named so it's not overwritten. Also, you can use the TCK summary that I created for GlassFish, once [this PR](https://github.com/eclipse-ee4j/glassfish/pull/23263) is merged (the TCK summary link will be: https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-interceptors/2.0/TCK-Results I don't think the Wiki link will be kept forever while the GlassFish website will not go away.

**Comment by kazumura** [comment]
@arjantijms  
Could you change the result URL to https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-interceptors/2.0/TCK-Results as @edbratt suggested.
Sorry for asking again.

**Comment by arjantijms** [comment]
@kazumura No problem, just updated it. Thanks!

**Comment by arjantijms** [comment]
As project lead of Interceptors I assert this is complete and be accepted.
